version: "3.7"

services:

  php-apache:
    build: ./.docker/php
    user: "1000:1000"
    container_name: php-apache
    volumes:
      - ./.docker/php/apache/apache2_logs:/var/log/apache2
      - type: bind
        source: ./.docker/php/apache/config.conf
        target: /etc/apache2/sites-available/000-default.conf
      - type: bind
        source: ./.docker/.env
        target: /var/www/laravel/.env
      - ./:/var/www/laravel
    ports:
      - 8080:80
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 127.0.0.1:3308:3306
    networks:
      - my-network
    environment:
      - MYSQL_ROOT_PASSWORD=4321
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - HOSTNAME=mysql
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8900:80
    networks:
      - my-network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      # for large import sql files
      - UPLOAD_LIMIT=4096m
      - MEMORY_LIMIT=4096m
      - MAX_EXECUTION_TIME=60000
    depends_on:
      - mysql

# Define networks
networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
